// ===== PRODUCT DATA =====
const PRODUCTS = [
  { id: 1, name: "Custom Photo Mug", category: "mugs", price: 299, originalPrice: 499, discount: 40, rating: 4.5, reviews: 128, image: "images/product-1.png", icon: "fa-mug-hot", badge: "Bestseller", description: "High-quality ceramic mug with your custom photo or design. Perfect for gifting.", features: ["11oz ceramic mug", "Dishwasher safe", "Vibrant print quality", "Custom photo/text", "Free delivery above ₹499"] },
  { id: 2, name: "Magic Color Changing Mug", category: "mugs", price: 399, originalPrice: 599, discount: 33, rating: 4.3, reviews: 89, image: "images/product-2.png", icon: "fa-mug-hot", badge: "Popular", description: "Heat-sensitive mug that reveals your design when filled with hot liquid.", features: ["11oz magic mug", "Heat-sensitive coating", "Custom design", "Great gift idea", "Microwave safe"] },
  { id: 3, name: "Custom Printed T-Shirt", category: "tshirts", price: 449, originalPrice: 699, discount: 36, rating: 4.6, reviews: 215, image: "images/product-3.png", icon: "fa-shirt", badge: "New", description: "Premium quality cotton t-shirt with your custom design, logo or photo.", features: ["100% cotton", "Available S-XXL", "Vibrant DTF print", "Washable design", "Unisex fit"] },
  { id: 4, name: "Polo T-Shirt Custom Print", category: "tshirts", price: 599, originalPrice: 899, discount: 33, rating: 4.4, reviews: 67, image: "images/product-4.png", icon: "fa-shirt", description: "Premium polo t-shirt with custom embroidery or print for corporate/personal use.", features: ["Premium polo fabric", "Custom logo/text", "Corporate gifting", "Available all sizes", "Bulk discounts available"] },
  { id: 5, name: "Custom Home Name Plate", category: "nameplate", price: 349, originalPrice: 549, discount: 36, rating: 4.7, reviews: 312, image: "images/product-5.png", icon: "fa-house", badge: "Trending", description: "Beautiful customized name plate for your home with your family name and design.", features: ["Acrylic/Wood material", "Custom name & design", "Weather resistant", "Easy installation", "Multiple sizes"] },
  { id: 6, name: "Office Desk Name Plate", category: "nameplate", price: 299, originalPrice: 449, discount: 33, rating: 4.5, reviews: 98, image: "images/product-6.png", icon: "fa-briefcase", description: "Professional desk name plate for office use with custom name and designation.", features: ["Premium acrylic", "Custom name & title", "Elegant design", "Multiple colors", "Corporate gifting"] },
  { id: 7, name: "Custom Photo Frame", category: "gifts", price: 399, originalPrice: 599, discount: 33, rating: 4.6, reviews: 178, image: "images/product-7.png", icon: "fa-image", badge: "Gift", description: "Beautiful custom photo frame with your favorite memories. Perfect for gifting.", features: ["Premium wood/acrylic", "Custom photo print", "Multiple sizes", "Gift packaging", "Free personalization"] },
  { id: 8, name: "Custom Cushion Cover", category: "gifts", price: 349, originalPrice: 499, discount: 30, rating: 4.4, reviews: 134, image: "images/product-8.png", icon: "fa-couch", description: "Soft cushion cover with your custom photo or design. Great home decor gift.", features: ["Soft polyester", "Custom photo print", "16x16 inch", "Zipper closure", "Washable"] },
  { id: 9, name: "Spiritual Om Name Plate", category: "spiritual", price: 449, originalPrice: 649, discount: 31, rating: 4.8, reviews: 256, image: "images/product-9.png", icon: "fa-om", badge: "Divine", description: "Beautiful spiritual name plate with Om symbol and custom family name. Auspicious home decor.", features: ["Premium material", "Om symbol design", "Custom name", "Vastu friendly", "Auspicious gifting"] },
  { id: 10, name: "Custom Spiritual Amulet", category: "spiritual", price: 249, originalPrice: 399, discount: 38, rating: 4.5, reviews: 89, image: "images/product-10.png", icon: "fa-star-and-crescent", description: "Personalized spiritual amulet with custom engraving. Blessed and auspicious.", features: ["Premium metal", "Custom engraving", "Spiritual design", "Gift packaging", "Blessed item"] },
  { id: 11, name: "Custom Keychain", category: "gifts", price: 199, originalPrice: 299, discount: 33, rating: 4.3, reviews: 445, image: "images/product-11.png", icon: "fa-key", badge: "Budget", description: "Personalized keychain with your photo, name or custom design.", features: ["Metal/acrylic", "Custom photo/text", "Durable print", "Compact size", "Bulk orders available"] },
  { id: 12, name: "Custom Water Bottle", category: "gifts", price: 499, originalPrice: 799, discount: 38, rating: 4.5, reviews: 167, image: "images/product-12.png", icon: "fa-bottle-water", description: "Stainless steel water bottle with custom design or company logo.", features: ["Stainless steel", "Custom print/logo", "500ml capacity", "Leak-proof", "Corporate gifting"] },
];

function getProductById(id) {
  return PRODUCTS.find(p => p.id === parseInt(id));
}

function getProductsByCategory(cat) {
  if (!cat || cat === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === cat);
}
